server.port=8443
server.ssl.enabled=true
server.ssl.key-store=${SSL_KEY_STORE:file:./config/bankxyz-dev.p12}
server.ssl.key-store-password=${SSL_KEY_STORE_PASSWORD:changeit}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=${SSL_KEY_ALIAS:bankxyz-dev}
server.ssl.client-auth=none
